name: CI/CD Pipeline with Docker and Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start

    - name: Set Docker to Minikube's environment
      run: |
        eval $(minikube -p minikube docker-env)

    - name: Build Docker image for Minikube
      run: |
        docker build -t my-app:latest .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml

    - name: Expose the application
      run: |
        kubectl expose deployment my-app --type=LoadBalancer --port=5000

    - name: Get Minikube URL
      run: |
        minikube service my-app --url
